import ClientLayout from '@/app/ClientLayout';
import type { Metadata } from 'next';
import './globals.css';
// import Header from '@/components/header/Header';
// import { useActiveToken } from '@/hooks/useActiveToken';

export const metadata: Metadata = {
  title: 'Time Machine',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { data: active } = useActiveToken();
  return (
    <html lang="en">
          <head>
        {/* load Inter from Google */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        />
      </head>
      <body className='max-w-screen-2xl mx-auto'>
        {/* <Header /> */}
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
