import ClientLayout from "@/app/ClientLayout";
import type { Metadata } from "next";
import "./globals.css";
import { HowItWorksProvider } from "@/contexts/HowItWorksContext";
// import Header from '@/components/header/Header';
// import { useActiveToken } from '@/hooks/useActiveToken';

export const metadata: Metadata = {
  title: "Time Machine",
  description: "Generated by create next app",

  openGraph: {
    title: 'Time Machine',
    description: 'Step into the time machine.\nYour prediction is encrypted and lost to time.\nWhen the capsule reopens, truth comes to light.\nAnd rewards those who saw it coming.',
    url: 'https://timemachine.fairblock.network/',
    siteName: 'Time Machine',
    images: [
      {
        url: 'https://drive.google.com/uc?export=view&id=1otvE6P1RHEu3dKMjQCo4yFFeQaYdvjTr',
        width: 1200,
        height: 630,
        alt: 'Time machine',
      },
    ],
    type: 'website',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const { data: active } = useActiveToken();
  return (
    <html lang="en">
      <head>
        {/* load Inter from Google */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
        />
      </head>
      <body className="font-neue">
        {/* <Header /> */}
        <HowItWorksProvider>
          <ClientLayout>{children}</ClientLayout>
        </HowItWorksProvider>
      </body>
    </html>
  );
}
