/* app/page.tsx */
import ClientHome from './ClientHome';
import type { Metadata } from "next";

export const dynamic = 'force-static';

export const metadata: Metadata = {
  title: "Time Machine",
  description: "Generated by create next app",

  openGraph: {
    title: 'Time Machine',
    description: 'Step into the time machine.\nYour prediction is encrypted and lost to time.\nWhen the capsule reopens, truth comes to light.\nAnd rewards those who saw it coming.',
    url: 'https://timemachine.fairblock.network/',
    siteName: 'Time Machine',
    images: [
      {
        url: 'https://res.cloudinary.com/dgfxugcho/image/upload/v1752080274/og-image_ibkpfd.jpg',
        width: 1200,
        height: 630,
        alt: 'Time machine Preview',
      },
    ],
    type: 'website',
  },
};

export default function Page() {
  return <ClientHome />;
}